# Generated by Django 6.0.4 on 2026-05-14 22:42

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCategoria', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Competidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCompetidor', models.CharField(max_length=30)),
                ('nombre_competidor', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idReceta', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=80)),
                ('instrucciones', models.TextField()),
                ('tiempo_preparacion', models.IntegerField(help_text='Tiempo en minutos')),
                ('dificultad', models.CharField(choices=[('BAJA', 'Baja'), ('MEDIA', 'Media'), ('ALTA', 'Alta')], default='BAJA', max_length=10)),
                ('imagenReceta', models.ImageField(blank=True, null=True, upload_to='receta/')),
            ],
        ),
        migrations.CreateModel(
            name='Tarifa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_tarifa', models.CharField(max_length=20)),
                ('porcentaje_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('idUsuario', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=30)),
                ('apellidos', models.CharField(max_length=50)),
                ('tipo_usuario', models.CharField(choices=[('B2C', 'B2C'), ('B2B', 'B2B'), ('ADMIN', 'Admin')], default='B2C', max_length=20)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('direccion_envio', models.TextField(blank=True, null=True)),
                ('cif_nif', models.CharField(blank=True, max_length=20, null=True)),
                ('razon_social', models.CharField(blank=True, max_length=100, null=True)),
                ('direccion_fiscal', models.TextField(blank=True, null=True)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('tarifa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='usuarios_tarifa', to='app.tarifa')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Carrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='carrito', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CarritoGuardado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCarrito', models.CharField(max_length=30)),
                ('nombre_carrito', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateField(auto_now_add=True)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='carritos_guardados', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idPedido', models.CharField(max_length=30)),
                ('fecha_pedido', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ENVIADO', 'Enviado'), ('ENTREGADO', 'Entregado'), ('CANCELADO', 'Cancelado')], default='PENDIENTE', max_length=20)),
                ('total_pedido', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('pdf_factura', models.FileField(blank=True, null=True, upload_to='facturas/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_usuario', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('calibre', models.CharField(blank=True, max_length=50, null=True)),
                ('es_ecologico', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('imagenProducto', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='productos_categoria', to='app.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='LineaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idLinea', models.CharField(max_length=30)),
                ('cantidad', models.IntegerField()),
                ('precio_unitario_aplicado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lineas_pedido', to='app.pedido')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ventas_producto', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemCarrito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('carrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_carrito', to='app.carrito')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_en_carritos', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='ProductoCompetidor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idProdCompetidor', models.CharField(max_length=30)),
                ('nombre', models.CharField(max_length=50)),
                ('cantidad', models.TextField(blank=True, null=True)),
                ('origen', models.CharField(blank=True, max_length=50, null=True)),
                ('calibre', models.CharField(blank=True, max_length=50, null=True)),
                ('es_ecologico', models.BooleanField(default=False)),
                ('precio_base', models.DecimalField(decimal_places=2, max_digits=10)),
                ('imagen_url', models.URLField(blank=True, max_length=500, null=True)),
                ('analisis_ia', models.TextField(blank=True, null=True)),
                ('competidor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos_del_competidor', to='app.competidor')),
                ('producto_san_blas', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comparativas_competidores', to='app.producto')),
            ],
        ),
        migrations.CreateModel(
            name='IngredienteReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idIngrediente', models.CharField(max_length=30)),
                ('cantidad', models.CharField(max_length=50)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas_donde_aparece', to='app.producto')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingredientes_de_receta', to='app.receta')),
            ],
        ),
    ]
