# Generated by Django 6.0.4 on 2026-05-18 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_usuario_saldo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagenProducto',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='receta',
            name='imagenReceta',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
